### ISSUE TITLE
Default null values for excel readers

### ISSUE THREAD

**Issue by davinov** [ToucanToco/peakina#115]
Why do we have a default with no null value at all for excel reading? https://github.com/ToucanToco/peakina/blob/main/peakina/readers/excel.py#L244
The list provided by pandas (by default) seems sensible, is there a particular reason to avoid it?
@Sanix-Darker @PrettyWood 

More context: today, we use a specific list in Laputa. This could be the concern of peakina (providing by default a dataframe with correct types) instead of a Laputa one.

**Comment by Sanix-Darker** [comment]
Hey @davinov , you're right, we should not change that value to False, we had this discussion (for csv) also here : https://github.com/ToucanToco/laputa/pull/4993#issuecomment-1055485743 !

**Comment by davinov** [comment]
Feature aborted! We reverted to using pandas excel reader
